local luaunit = require("luaunit")

require("Tests.WoWEnvironment")

DoWoWFile("Tests/FilterFactory/CharacterBlacklist.lua")
DoWoWFile("Tests/FilterFactory/CharacterWhitelist.lua")
DoWoWFile("Tests/FilterFactory/Combined.lua")
DoWoWFile("Tests/FilterFactory/PatternWhitelist.lua")
DoWoWFile("Tests/FilterFactory/PatternBlacklist.lua")
DoWoWFile("Tests/FilterFactory/CharacterCopper.lua")
DoWoWFile("Tests/MoneyTable/Factory/Characters.lua")
DoWoWFile("Tests/MoneyTable/Factory/Realms.lua")
DoWoWFile("Tests/MoneyTable/Factory/RealmsWithCombinedFactions.lua")
DoWoWFile("Tests/MoneyTable/Map.lua")
DoWoWFile("Tests/MoneyTable/MapFields.lua")
DoWoWFile("Tests/MoneyTable/ConvertTypes.lua")
DoWoWFile("Tests/DB/Migrations/Global/001-NormalizeRealmNames.lua")
DoWoWFile("Tests/DB/Migrations/Profile/001-MigrateFilters.lua")
DoWoWFile("Tests/DB/Migrations/Profile/002-MigrateFilters.lua")
DoWoWFile("Tests/DB/Migrations/Profile/003-AddTypeConfigDefaults.lua")
DoWoWFile("Tests/DB/Migrations/Profile/004-CharacterCopperToGenericCopper.lua")

os.exit(luaunit.LuaUnit.run())
