name: Test

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install luarocks
        run: sudo apt-get install luarocks
      - name: Install luaunit
        run: sudo luarocks install luaunit
      - name: Fetch dependencies
        uses: BigWigsMods/packager@v2
        with:
          # Skip all tasks other than checking out external repositories
          args: -c -d -l -z
      - name: Copy Libs directory
        run: cp -r .release/*/Libs .

      - name: Run tests
        run: lua Tests/Test.lua
